apiVersion: v1
kind: Service
metadata:
  name: deepak-app-svc
  labels:
    run: deepak
spec:
  selector:
    app: deepak
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort